import { User } from './user.model';
import { ProductNeed } from './product-need.model';
import { Shipment } from './shipment.model';
import { OrderItem } from './order-item.model';
import { Payment } from './payment.model';

export interface Order {
  additionalDiscount?: number;
  applicableCustomerCredit?: number;
  applicableGiftCardCredit?: number;
  budget?: number;
  campaign?: string;
  cashRefund?: number;
  comments?: string;
  cost?: number;
  customer?: User;
  customerComments?: string;
  customerCreditRefund?: number;
  customerOrderNumber?: string;
  dateAbandoned?: Date;
  dateAccepted?: Date;
  dateCancelled?: Date;
  dateCompleted?: Date;
  dateCreated?: Date;
  dateDelivered?: Date;
  dateFinalized?: Date;
  dateFirstPreviewWarningSent?: Date;
  dateFirstRecoveryEmailSent?: Date;
  dateRejected?: Date;
  dateReturned?: Date;
  dateReviewedByCustomer?: Date;
  dateSecondPreviewWarningSent?: Date;
  dateSecondRecoveryEmailSent?: Date;
  dateSentForPreview?: Date;
  dateShipped?: Date;
  dateShippedBack?: Date;
  dateThirdRecoveryEmailSent?: Date;
  deleted?: boolean;
  discount?: number;
  giftCardCreditRefund?: number;
  grossPrice?: number;
  id?: string;
  invoiceValue?: number;
  isPreviewRequired?: boolean;
  lastUpdated?: Date;
  netPrice?: number;
  orderItems?: OrderItem[];
  orderNumber?: number;
  outboundShippingCost?: number;
  payments?: Payment[];
  previewNotes?: string;
  previewNumber?: number;
  productNeeds?: ProductNeed[];
  promoCode?: string;
  retailValue?: number;
  returnLabel?: string;
  returnShippingCost?: number;
  returnShippingStatus?: string;
  returnTrackingNumber?: string;
  shipments?: Shipment[];
  shippedValue?: number;
  shippingLabel?: string;
  shippingStatus?: string;
  specialInstructions?: string;
  status?: string;
  totalCreditRefund?: number;
  totalRefund?: number;
  trackingNumber?: string;
  type?: string;
  value?: number;
  virtualOrderItems?: OrderItem[];
  xCustomer?: string;
}
