import { Address } from './address.model';
import { Subscription } from './subscription.model';
import { Order } from './order.model';
import { BrandDislike } from './brand-dislike.model';

export interface User {
  addresses?: Address[];
  brandDislikes?: BrandDislike[];
  id?: string;
  deleted?: boolean;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  status?: string;
  creditAmount?: number;
  giftCardCreditAmount?: number;
  statedHeight?: string;
  statedWeight?: number;
  statedWaist?: number;
  statedInseam?: string;
  statedNeck?: string;
  statedSleeve?: string;
  statedShirtSize?: string;
  statedShirtFit?: string;
  statedShirtLength?: string;
  statedShoeSize?: string;
  statedShortSize?: string;
  statedPantFit?: string;
  age?: string;
  dateOfBirth?: Date;
  signUpDate?: Date;
  signUpMethod?: string;
  acquisitionSource?: string;
  campaign?: string;
  testScenario?: string;
  paymentToken?: string;
  paymentCustomerId?: string;
  password?: string;
  facebookId?: string;
  notesOld?: string;
  feedback?: string;
  dateLastEmailHookSent?: Date;
  orders?: Order[];
  startedOrder?: boolean;
  selectedBudget?: boolean;
  selectedClothing?: boolean;
  subscriptions?: Subscription[];
  dateCreated?: Date;
  lastUpdated?: Date;
  role?: string;
}
